--- 
title: "Studiehandleiding Module Lead Generation"
subtitle: "Isatis Academy"
author: "<a href='https://www.linkedin.com/in/witektenhove/' target='_blank'>Witek ten Hove</a> & <a href='https://www.linkedin.com/in/roellinssen/' target='_blank'>Roel Linssen</a>"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "Deze handleiding beschrijft de didactische opzet en structuur van de module Lead Generation."
---

# Welkom

## Isatis Academy

Isatis Academy is het opleidings- en onderzoeksintituut van de <a href="https://www.isatis.nl/" target="_blank">Isatis Groep</a>. We zijn een open community van didactische en technische experts met een passie voor kennisontwikkeling en -deling. Ons doel is onze interne, zakelijke en maatschappelijke partners te helpen groeien door prachtige innovatie, boeiend onderwijs en laagdrempelige toegang tot kennis te bieden.

## Module Lead Generations (LG)

### Lead Generation
Het doel van *Lead Generation* is klanten optimaal ondersteunen bij hun online aankoopbeslissingen.

### Voor wie?
Je bent nieuwsgierig naar online gedrag van mensen en hoe ze reageren op verschillende impulsen. Binnen het LG-team kun je verschillende rollen vervullen. Echter voor een aantal gebieden ben jij de expert en hiermee draag je bij aan de unieke identiteit van het team en jullie product.

### Rollen
Een LG-team bestaat uit de volgende rollen en de bijbehorende verantwoordelijkheden:

```{r, echo=FALSE, message=FALSE}
library(knitr)
rolDF <- read.csv2("book/data/rollen.csv")
kable(
  rolDF, booktabs = TRUE,
  caption = 'Overzicht van competenties en levels voor Content Marketeer'
)
```

## Onderwijsteam
